name: ey
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.10 
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/seva_setu_logo.png
    - assets/images/seva_setu_logo.png
    - assets/images/rashtriya_swasthya.png
    - assets/images/pradhan_mantri.png
    - assets/images/esic.png
    - assets/images/deendayal.png
    - assets/images/pradhan_mantri_awas.png
    - assets/images/national_family.png
    - assets/images/rashtriya_parivarik.png
    - assets/images/pradhan_mantri_jan.png
    - assets/images/atal_pension.png
    - assets/images/sukanya_samriddhi.png
    - assets/images/pradhan_mantri_jeevan.png
    - assets/images/kisan_credit.png
    - assets/images/national_electric.png
    - assets/images/pradhan_mantri_gram.png
    - assets/images/pm_ebus.png
    - assets/images/national_highway.png